### ISSUE TITLE
Problems of French translation under archlinux

### ISSUE THREAD

**Issue by roxfr** [linuxdeepin/deepin-screen-recorder#27]
There are problems of French translation under archlinux
See image below

<a href="http://zupimages.net/viewer.php?id=19/25/6sbf.png"><img src="https://zupimages.net/up/19/25/6sbf.png" alt="" /></a>

**Comment by BLumia** [comment]
You can help translate "Deepin Voice Recorder" by [join the community translation team on Transifex](https://www.transifex.com/linuxdeepin/deepin-screen-recorder/) :)

**Comment by roxfr** [comment]
Hello,
I am already registered to transifex on the deepin linux project.
I do not understand why the translation does not work on Archlinux ?

<a href="http://zupimages.net/viewer.php?id=19/26/n0j8.png"><img src="https://zupimages.net/up/19/26/n0j8.png" alt="" /></a>

**Comment by BLumia** [comment]
Thx for the ino! Will update the translation file later!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
