### ISSUE TITLE
Default photo, videos and gif folder

### ISSUE THREAD

**Issue by pangpangpang3** [linuxdeepin/deepin-screen-recorder#3]
SalahAdDin commented on May 15
Hi, thanks for this great work.

GIF works very good with the screen recorder software.

But i think that all gif, videos and photos have to be in his respective user folders and not in the desktop.
Also put settings for customization will be great.

Thank you.

**Comment by manateelazycat** [comment]
You can change save place through config file: ~/.config/deepin/deepin-screen-recorder/config.conf

Something like:
[fileformat]
save_directory=/home/andy/Desktop

**Comment by rafaeldev** [comment]
Any update about that configuration?
For final user this is not reasonable solution...
