### ISSUE TITLE
Only works on monitor where the mouse was in during startup

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/deepin-screen-recorder#4]
Great piece of software! Thanks a lot!

Nontheless there is an issue I noticed:

I have a three monitor environment and no matter which monitor I am starting the screen recorder from, it only works on the primary one.

**Comment by DasJott** [comment]
Change this to: Works only on the monitor the mouse was in while startup. Could live with that...

**Comment by xereda** [comment]
I have the same problem.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
