### ISSUE TITLE
[Feature Request] support screenshot save choice as: saveToClipboard **or** saveAsFile

### ISSUE THREAD

**Issue by iamhyc** [linuxdeepin/deepin-screen-recorder#49]
简而言之：希望截图 **保存到剪切板** 和 **保存为文件** 这两个选项可以独立可以独立；
即支持以下选项组合 a) 只保存到剪切板 b) 保存到剪切板同时不保存为文件 c) 不保存到剪切板但保存为文件，但不支持 d) 都不保存

虽然这里的代码和deepin v20 （1001）公测的不一样，~~但目前看到 subToolWidget::initShotLabel 中OptionMenu的配置 saveToDesktopAction/saveToPictureAction/... 通过if-else来实现互斥操作。~~ （ok，需要两个"save_op"并且t_saveGroup使用 QActionGroup::ExclusionPolicy::None，不能简单的用setExclusive来实现，如果可以的话我可以来提pull request）
我认为可以按照上面提到的逻辑来重新实现，这样用起来更方便 。

如果可以的话，我可以提出pull request吗？

**Comment by iamhyc** [comment]
hi，我注意到你们更新了issue提交指南，所以希望有人能回复下这个issue @z966768

**Comment by z966768** [comment]
@deepin-CD 麻烦处理一下

**Comment by iamhyc** [comment]
@deepin-CD 请回复一下是否可以增加这个feature，谢谢。

**Comment by deepin-CD** [comment]
@iamhyc  该需求已经实现，请拉取最新的uos分支代码

**Comment by iamhyc** [comment]
@deepin-CD  已确认uos branch最新代码**并未实现**，请注意我的描述：允许同时 保存为截图 **或者** 保存为文件，而不是互斥选择。

另外在新引入的xdg-desktop-portal-kde中疑似存在依赖缺失问题（通过apt build-dep拉取依赖）
缺少的依赖：libgbm-dev, libavcodec-dev, libavformat-dev, libavfilter-dev, libavdevice-dev
请确认下是否在开发仓库中存在这个问题。

**Comment by deepin-CD** [comment]
@iamhyc 想先明确下需求：当前截图后有四个选项：1）剪贴板、2）图片、3）桌面、4）指定位置，你的需求是想要实现，图片和指定位置能够复选吗？为什么需要这样的应用场景呢？
如果你的需求是，想要实现剪贴板和指定位置，勾选指定位置，也会保存到剪贴板的。

**Comment by iamhyc** [comment]
> @iamhyc 想先明确下需求：当前截图后有四个选项：1）剪贴板、2）图片、3）桌面、4）指定位置，你的需求是想要实现，图片和指定位置能够复选吗？为什么需要这样的应用场景呢？
> 如果你的需求是，想要实现剪贴板和指定位置，勾选指定位置，也会保存到剪贴板的。

现在保存为文件（指定位置），会同时默认保存到剪贴板？试了下确实是这样。

那我的需求差不多是这样，但还支持“**保存到指定位置，但不保存到剪贴板**”，这样不会影响到剪贴板之前的内容；
不过这的场景可能比较少见，目前看起来没必要再改了，谢谢！

P.S. 但这个默认必然保存到剪贴板符合使用预期吗？建议修改下文字提示内容。
