### ISSUE TITLE
Change frame rate

### ISSUE THREAD

**Issue by zelislavsirka** [linuxdeepin/deepin-screen-recorder#5]
Hello,
Is there a way to change the frame rate in Deepin Screen Recorder?

**Comment by manateelazycat** [comment]
Did you mean change frame rate of mp4?

**Comment by zelislavsirka** [comment]
Yes, I mean frame rate of mp4.

Thanks

**Comment by manateelazycat** [comment]
@zelislavsirka https://github.com/linuxdeepin/deepin-screen-recorder/commit/a3b6a2b423e2e63b4d65abc0ad856e1de140a440 has add support.

Update install newest version, change ~/.config/deepin/deepin-screen-recorder options:

mkv_framerate and mp4_framerate
