### ISSUE TITLE
mp4格式录制文件位0b

### ISSUE THREAD

**Issue by sjditadmin** [linuxdeepin/deepin-screen-recorder#6]
"[x11grab @ 0xe2f1a05ec0] Stream #0: not enough frames to estimate rate; consider increasing probesize"
"Input #0, x11grab, from ':0.0+348,183':"
"  Duration: N/A, start: 1510219454.473007, bitrate: N/A"
"    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1224x659, 25 fps, 1000k tbr, 1000k tbn, 1000k tbc"
"Stream mapping:"
"  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))"
"Press [q] to stop, [?] for help"
"[libx264 @ 0xe2f1a0f220] height not divisible by 2 (1224x659)"
"Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height"
"Conversion failed!"

**Comment by manateelazycat** [comment]
Patch has fixed this problem: https://github.com/linuxdeepin/deepin-screen-recorder/commit/22877d7345e4574dc74c67c1c783531adbdde35e
