### ISSUE TITLE
Hopefully deepin-screen-recorder can add a new feature,pin image to desktop

### ISSUE THREAD

**Issue by bronzus** [linuxdeepin/deepin-screen-recorder#61]
I think this is a feature that can significantly improve office productivity.Since deepin-screen-recorde didn't have this feature, I had to install an extra tool,flameshot

**Comment by dfc643** [comment]
nice idea

**Comment by deepin-CD** [comment]
Thanks for your good suggestions, and we will follow up to add this feature.

**Comment by Wesly186** [comment]
I also install another tool flameshot. if deepin can support this future，flameshot can be uninstall, I prefer to use deepin origin software

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
