### ISSUE TITLE
Cannot use on Arch Linux 

### ISSUE THREAD

**Issue by denisgranha** [linuxdeepin/deepin-screen-recorder#64]
Since the last update, I cannot tell what version was running before, but the current one that is giving me issues:

deepin-screen-recorder 1230 (from command line)

or: deepin-screen-recorder-5.8.0.61-1 (from pacman)

I get this by executing it through command line:

```
2021-01-18, 14:16:46.722 [Debug  ] [                                                         0] ConfigSettings: "effect" "is_blur" QVariant(bool, false)
2021-01-18, 14:16:46.729 [Debug  ] [                                                         0] ConfigSettings: "effect" "is_mosaic" QVariant(bool, false)
2021-01-18, 14:16:46.729 [Debug  ] [                                                         0] Setting file: "/home/denis/.config/deepin/deepin-screen-recorder.conf"
2021-01-18, 14:16:46.733 [Debug  ] [                                                         0] config changed
2021-01-18, 14:16:46.733 [Debug  ] [                                                         0] ConfigSettings: "common" "themeType" QVariant(int, 1)
2021-01-18, 14:16:46.760 [Debug  ] [                                                         0] is zhao xin: ""
2021-01-18, 14:16:46.823 [Debug  ] [                                                         0] screen rect: QRect(0,0 3840x2160)
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 409, resource id: 0, major code: 20 (GetProperty), minor code: 0
```

It doesn't show anything from deepin-screen-recoder and it won't let you use any app until you click ESCAPE so deepin-screen-recorder is finalized.

I don't know what to do for debugging this further. Please let me know if I can provide you with more data

**Comment by justforlxz** [comment]
Do you mean that no operations can be performed after startup?

**Comment by denisgranha** [comment]
before the update it would show the deepin icon and tooling for screenrecording, I would select the area to screenshot and that was it. 

Now nothing shows, it just prevents me from using any app until pressing Escape.

**Comment by 453647684** [comment]
Before you get stuck, can you select the screenshot area?

**Comment by ztoiax** [comment]
I had the same problem

**Comment by denisgranha** [comment]
I tried to do some select as if the app behave normally even though I don't see it, but nothing happens. THe only way to exit from the screen-recorder that I found was pressing ESCAPE.

Maybe I can record something with my phone, but I had another unrelated issues with the bootloader so I couldn't send a video yet 😅

**Comment by deepin-CD** [comment]
We have recorded the questions you submitted. Thank you very much for your support．

In order to know more about your problems, you'd better record a short video with your mobile phone and send it to my email address: houlei@uniontech.com

**Comment by RobbinDG** [comment]
Is there any progress on this issue? I am running into the exact same thing. However, I have found that a very small window appears in the top left if I hover over it with my mouse. Additionally, the text "0X0" is printed on screen. I can actually select an area in this (though it only covers a small fraction of the entire screen, so isn't usable). I can see a piece of the GUI that used to appear before. 
Additionally, I found that by looking for alternatives, flameshot seems to give similar errors. This leads me to believe this is not actually an issue with deepin screen recorder, but rather an arch/Qt related problem. I'm sadly incredibly underqualified to confirm any of this.

My system details:
- Arch linux (most recent version as of the time of writing)
- WM: bspwm
- qmake -query QT_VERSION ---> 5.12.2 (Qt version I think, once again, not familiar with Qt).

**Comment by RobbinDG** [comment]
Supplementary images to my previous comment. 
First image: immediately after calling deepin-screen-shot.
Second image: the 0X0 text that appears after hovering over the outline box
Third image: after selecting a small region within the box

![IMG_20210211_131655.jpg](https://user-images.githubusercontent.com/32838181/107635489-88f52600-6c6b-11eb-9e1d-1828d3e7a014.jpg)![IMG_20210211_131708.jpg](https://user-images.githubusercontent.com/32838181/107635501-8c88ad00-6c6b-11eb-85c9-9d6cc9cd80a3.jpg)![IMG_20210211_131718.jpg](https://user-images.githubusercontent.com/32838181/107635506-8e527080-6c6b-11eb-94e8-bb7b91d31947.jpg)

**Comment by deepin-CD** [comment]
Sorry about this. We have reproduced this problem. The reason is that the new version uses the D-bus interface provided by DDE. 
We are working on solving this compatibility bug.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
