### ISSUE TITLE
[suggestion] deepin-screen-recoder should add a function that can pin a image to the desktop like flameshot, it is helpful

### ISSUE THREAD

**Issue by Wesly186** [linuxdeepin/deepin-screen-recorder#65]
![image](https://user-images.githubusercontent.com/16346644/107138839-e595cf80-6951-11eb-8057-60b35537b4aa.png)

**Comment by uos-hl** [comment]
We will seriously consider your suggestion. Thank you for your suggestion.

**Comment by deepin-CD** [comment]
Many thanks for your suggestion, we will seriously consider your suggestion.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed. Please reopen the issue if there're any new updates.
