### ISSUE TITLE
D-Bus method "StartScreenshotFor3rd " cannot save screenshots with specific filename

### ISSUE THREAD

**Issue by jiangzc** [linuxdeepin/deepin-screen-recorder#67]
System:  deepin v20.1
deepin-screen-recorder: version 5.8.1

Call D-Bus method StartScreenshotFor3rd , passed the argument "/tmp/123.png" as filepath with specific filename. But the  screenshot saved in ~/Pictures folder, instead of the folder I provided .

D-Bus method SavePathScreenshot works well.

---
---
![image](https://user-images.githubusercontent.com/13901512/108166765-9a3ca780-712f-11eb-9865-70938e3d5f51.png)

**Comment by jiangzc** [comment]
Compare Line 885 with Line 903.
https://github.com/linuxdeepin/deepin-screen-recorder/blob/8da36e2569d0a44a6fd821005329c91ea78d0d59/src/main_window.cpp#L883-L915

---
My suggestion : 

https://github.com/linuxdeepin/deepin-screen-recorder/blob/8da36e2569d0a44a6fd821005329c91ea78d0d59/src/main_window.cpp#L903

=>
```cpp
    if (path == "" || (!QFileInfo(path).dir().exists()) { 
```

**Comment by deepin-CD** [comment]
The D-Bus interface is a special interface provided by screenshots to third-party applications.

It is agreed that the incoming parameter is the save directory. Returns the absolute path of the saved image.

If you need to customize the file name, please use the ‘SavePathScreenshot’ interface.

**Comment by jiangzc** [comment]
Thanks for your reply.  I noticed that the returned path can be received after connecting to the "Done" signal.
