### ISSUE TITLE
[Feature Request] Remember last used configuration

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/deepin-screen-recorder#69]
It would be neat to let the application remember your preferences. When you open the app and have previously used settings.

**Comment by 453647684** [comment]
Deepin-screen-recorder saved the user's settings, and restore the configuration when opening the app.
Please provide the details of the problem, and the version number.

**Comment by vesterlay** [comment]
The version of deepin-screen-recorder is 5.8.1-1
The utility doesn't remember that I don't want to use a microphone and it always selects to capture microphone and audio. I can provide a video of this issue if necessary.

**Comment by deepin-CD** [comment]
During the screen recording process, we did not save the audio configuration. And, we will turn on the microphone (if there is a microphone) and the recording of system audio by default. This problem has been reported to the product manager.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed. Please reopen the issue if there're any new updates.
