### ISSUE TITLE
Do not save mp4

### ISSUE THREAD

**Issue by simnandez** [linuxdeepin/deepin-screen-recorder#7]
If I make a screen record in gif it works perfectly, but if I make it in mp4 it does not create any file. 

The log error is: "Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x560fd57b0a60] Cannot open display :0.0+837,201, error 1."
":0.0+837,201: Input/output error"

if I make a  echo $DISPLAY I get :1 

I think it would be a good solution to be able to indicate the display by configuration (config.conf file)

**Comment by manateelazycat** [comment]
All X11 tools run on DISPLAY :0 , if you want deepin-screen-recorder recording DISPLAY 1.

You should use command like blow:

export DISPLAY=:1 && deepin-screen-recorder
