### ISSUE TITLE
[Feature Request] Allow to record while in-game 

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/deepin-screen-recorder#70]
Right now when you get into the game, Deepin automatically turns off window effects altogether with an ability to record your screen. I wonder if it's possible to keep recording available. It find this tool very powerful and making this possible would let people conveniently share their game experience with friends.

**Comment by 453647684** [comment]
When the window effects is turned off, the screen recording function is not supported.

**Comment by vesterlay** [comment]
The version is `5.8.1-1`

> If you are using the latest screenshot recording version, you can try to turn off the window effects before recording the screen.

That's exactly what I want. I can't do it on my version unfortunately.

**Comment by vesterlay** [comment]
@453647684 there is a white line on top and left corner https://youtu.be/GKUu2n9g4KQ. Can you reproduce?

**Comment by vesterlay** [comment]
https://user-images.githubusercontent.com/39202451/113411101-3e637080-93b5-11eb-9cd5-bf78b7dbadde.mp4

**Comment by deepin-CD** [comment]
We have fixed this issue in the new version that will be released recently. Thank you for your suggestions and attention.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed. Please reopen the issue if there're any new updates.
